### ISSUE TITLE
Add process to convert gestureRecognizer to Swift

### ISSUE THREAD

**Issue by Ryu0118** [Ryu0118/MagicIB#35]
# Todo
- [x] create IBGestureRecognizer class
- [x] create IBGestureRecognizer+generator
- [x]  Incorporate IBGestureRecognizer+generator into SwiftCodeGenerator
